language: node_js
node_js:
- 10.1.0
cache:
  yarn: true
script:
- yarn
- yarn workspace demo clean
- yarn workspace demo build --prefix-paths
- touch demo/public/.nojekyll
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  local-dir: "./demo/public"
  keep-history: false
  skip-cleanup: true
  target-branch: gh-pages
  on:
    branch: master
env:
  global:
    secure: esClukrTTIyjATwFcUzuUSC7/OZsRB8X3zzKSBySSSCzYXnBHGTI38s2n8mY7WSHVB+khE4H8p2gD0wsLcGYA2oiOXHNBZkR60tvkvMPK4mhDAHbQmgRArPjZY8pKt8UvH04ReJEq/KcdkcPjWL4fa0rpMuv6hgpt3Kl1U9ATifcmJ55+OG2VvfbATd1Wnq1jlb3lyTofBU72LfDlm0a+yNtTD+wLA5MEtRQtwm3je0NY24NPAXRd54szE2foF5wX5dYQTswdl6pob42mg7e+zdr2cHN88gdpkAKXrZtpK76q3UIXpGkI7TAK1j1AUJyIMFhRzVyUKWvChd1MKHfbfatOXV0h/uAWo5d3453OIhsIgyJz5AETdqm8J7N//V8jBCv/FfawlGam+oqppCo6UPX38f8SjLbITpwv4Zng2WZ4u3uWUiC5EBU0K9g8kQzHi8ukikI2+k1I5Ia/WsuF4HJ2M2bii0V0ExvRITIFf4vmf3Qk8nIJqhOBVSHkEMhcp7ysoE6+JV0bbGlkATuNOWUGwSDdpNQnukuI9RbEmAVWhlRReC7D1evzTW2epoft2wQ5vcce9Bx9gMbyAB7MbqLjP+Msw0KgtHY7qEYY1+mo1fH+Pdtfm2cTygDU5uZAIyUg4XBqly1s+oH6eHRLEtozRI+OO8ptNG6hBQoExQ=
